### ISSUE TITLE
begin_frame is not a file in the archive

### ISSUE THREAD

**Issue by tzzcl** [LeYangNwpu/A2Net#1]
Hi, I read your paper A2Net and it is really amazing work on action localization.

However, when I downloaded the feature on ActivityNet and tried to run it, it has the error that:

`
'begin_frame' is not a file in the archive.
`

and I manually looked into the feature file, it seems that for ActivityNet, the file does not have the 'begin_frame' key.

Can you explain that part?
Also, I want to know that the material you provides including 'cuhk_simple_share.json'. It is the classification result for ActivityNet. I want to know where does it come from? Is it come from the anet-cuhk 2016 or anet-cuhk 2017?

Thanks!

**Comment by VividLe** [comment]
There is a mistake with the link to features. I will update it assp and let you know.

cuhk_simple_share.json is the classification results for ActivityNet. It comes from anet-cuhk 2016.

**Comment by VividLe** [comment]
The data has been updated.
